name: "Deploy application using ansible"
description: "Deploy the application using ansible"

inputs:
  client_name:
    description: "Name of the client located on the ansible hosts that will run the playbook"
    required: true
  role_name:
    description: "Project role name"
    required: true
  ansible_inventory:
    description: "Inventory file name"
    required: false
  playbook:
    description: "Playbook name"
    required: true
  vault_file:
    description: "Vault file location"
    required: true
  working_directory:
    description: "Working directory where ansible is located"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run ansible
      shell: bash
      run: sudo ansible-playbook -i ${{ inputs.ansible_inventory }} -l ${{ inputs.client_name }} ${{ inputs.playbook }} -t ${{ inputs.role_name }} --vault-password-file ${{ inputs.vault_file }}
      working-directory: ${{ inputs.working_directory }}
